### ISSUE TITLE
Implement fullpage js on the website.

### ISSUE THREAD

**Issue by saranshbarua** [osdc/osdc.github.io#11]
[Link for fullpage js](https://alvarotrigo.com/fullPage/#firstPagel)

**Comment by ojas1234** [comment]
@saranshbarua I am interested. Can u guide me?

**Comment by saranshbarua** [comment]
@ojas1234 Sure. Have you read the docs in the link above?

**Comment by ojas1234** [comment]
@saranshbarua Yes.

**Comment by saranshbarua** [comment]
Then you are good to go. Create a branch and get started. If you need help, catch us on discord.

**Comment by ojas1234** [comment]
@saranshbarua What should be the content?

**Comment by saranshbarua** [comment]
The content should be the same as what has been added till now i.e the landing page and the about us section.

**Comment by saranshbarua** [comment]
I am closing this, since it is no longer needed.
