### ISSUE TITLE
Use a better component naming architecture

### ISSUE THREAD

**Issue by ryzokuken** [osdc/osdc.github.io#13]
Inviting comments from the community. Let's use this thread to decide what to use.

/cc @526avijitgupta @yashmehrotra @saranshbarua @priyansh1161

**Comment by saranshbarua** [comment]
@ryzokuken do we still need this?

**Comment by saranshbarua** [comment]
@ryzokuken any updates on this?

**Comment by ryzokuken** [comment]
It's too old, closing this.
