### ISSUE TITLE
Octokit functions not working for me

### ISSUE THREAD

**Issue by Yugandhartripathi** [osdc/osdc.github.io#20]
![image](https://user-images.githubusercontent.com/32102845/37866600-e64f855a-2fb2-11e8-8ce7-33c8a2c25bd7.png)
![image](https://user-images.githubusercontent.com/32102845/37866603-00dc9eda-2fb3-11e8-98d4-b3c4693be009.png)
I have searched around and it has something to do with webpack : https://github.com/andris9/encoding/issues/16 , https://github.com/kadirahq/lokka-transport-http/issues/22
I still can't get it to work for me

**Comment by saranshbarua** [comment]
@Yugandhartripathi did you run npm install or yarn?

**Comment by Yugandhartripathi** [comment]
@saranshbarua I used npm install

**Comment by saranshbarua** [comment]
Use yarn and it will work for you.

**Comment by Yugandhartripathi** [comment]
@ryzokuken told me it had something to do with github tokens how only limited views per day were allowed for free

**Comment by saranshbarua** [comment]
@Yugandhartripathi you tried yarn?

**Comment by Yugandhartripathi** [comment]
using windows right now will reboot and try in a few hours and update accordingly

**Comment by saranshbarua** [comment]
@Yugandhartripathi please try and let me know asap.

**Comment by Yugandhartripathi** [comment]
@saranshbarua It's working now

**Comment by saranshbarua** [comment]
Good. Closing this now.
