### ISSUE TITLE
Implement smooth scrolling

### ISSUE THREAD

**Issue by saranshbarua** [osdc/osdc.github.io#33]
On clicking the arrow on the landing page, it scrolls down abruptly. A smooth transition would look great.

**Comment by ryzokuken** [comment]
`jQuery.scrollTo`? 😛

**Comment by lucas-carl** [comment]
I would like to take on this issue :) #hacktoberfest

**Comment by lucas-carl** [comment]
Made a pull request #34

**Comment by saranshbarua** [comment]
Closing this since this is resolved in #34
