### ISSUE TITLE
Dropping the idea of adding google forms for giving talks

### ISSUE THREAD

**Issue by nightwarriorftw** [osdc/osdc.github.io#43]
@ryzokuken @saranshbarua 
I think rather than making a google form for talks we can let people make an issue if they want to give a talk and what's the topic of their talk in the meetups. We can do this in meetup repo itself .
Regards,
nightwarrior-xxx

**Comment by Yugandhartripathi** [comment]
Yeah I think that will be better because if we make forms then if we want to discuss on it for like details or time/date/venue clashes or rescheduling then we have to do it separately whereas with open/closed/subscribe/comment options in github issues it can all be done in one place.
We can instead make an event/notice board on the osdc site to show finalized talks with time and venue.

**Comment by nightwarriorftw** [comment]
Then let's wait for @ryzokuken and @saranshbarua  to respond

**Comment by ryzokuken** [comment]
Sounds fair.

**Comment by saranshbarua** [comment]
> We can instead make an event/notice board on the osdc site to show finalized talks with time and venue.

This seems like a good idea. We can redirect them to the CC's repo on github in case they want to submit a proposal. Wdyt @ryzokuken @Yugandhartripathi @nightwarrior-xxx ?

**Comment by Yugandhartripathi** [comment]
@saranshbarua sounds great to me. Let's put it in the pipeline and start the good work.

**Comment by ryzokuken** [comment]
@saranshbarua fair! Let's do it.

**Comment by ryzokuken** [comment]
Oh, and let's redirect them to osdc/meetups instead?

**Comment by nightwarriorftw** [comment]
@ryzokuken  Can you make it more clear ? In which case we should redirect them to osdc/meetups page .

**Comment by ryzokuken** [comment]
@nightwarrior-xxx 

> We can redirect them to the CC's repo on github in case they want to submit a proposal.

Redirect them to the osdc/meetups repo instead.

**Comment by sidntrivedi** [comment]
@ryzokuken @saranshbarua  Just to re-iterate this, can we add an issue template in this repository for talks? If anyone wants to propose a talk, they can just make an issue here as @nightwarrior-xxx suggested and we can ping them in the issue comment itself before the meetup in which we can include their talk? 

Also making an issue here itself will help in keeping track of meetups all at one place.

PS: ILUG-D follows a similar procedure and it seems pretty decent. We can have a look - https://github.com/ilugd/talks/issues . What do you say?

/cc: @osdc/2019-20

**Comment by ryzokuken** [comment]
@sidntrivedi012 yes! SingaporeJS also used a similar model and it works pretty well. I personally agree, but you should feel free to do what you feel like without waiting for my approval anyway.

**Comment by sidntrivedi** [comment]
@ryzokuken Cool then. Will make an issue template for proposing talks. Also, one can also request a talk by making issue here and adding a request label.
