### ISSUE TITLE
Deploy the website on netlify instead of surge

### ISSUE THREAD

**Issue by saranshbarua** [osdc/osdc.github.io#45]
@Yugandhartripathi @sidntrivedi012 like we discussed on the channel, let's move the website to netlify for better load times.

**Comment by saranshbarua** [comment]
Also, let's change the repo's description after the deployment.

**Comment by sidntrivedi** [comment]
Ok. But how are we gonna add the repository to netlify? Do we need to login with the github org 
creds ?

**Comment by saranshbarua** [comment]
The maintainer can use his account. Everything's free!

**Comment by saranshbarua** [comment]
Just do netlify init if you're using netlify-cli, build the project and then netlify deploy. That easy :)

**Comment by sidntrivedi** [comment]
@saranshbarua Cool. Doing it.

**Comment by sidntrivedi** [comment]
@saranshbarua https://osdc.netlify.com/ . 

Deployed through GUI not through CLI. In CLI, it was showing this error : 
![Screenshot 2019-08-29 at 12 54 13 AM](https://user-images.githubusercontent.com/31186013/63886302-d0481200-c9f7-11e9-9399-b3297da8c7ee.png)

Even though I had already run a `gatsby build`.

**Comment by sidntrivedi** [comment]
Oof. Had to just remove functions option from netlify.toml. Its deployed from CLI as well.

**Comment by ryzokuken** [comment]
This is done, closing this now. Thanks @sidntrivedi012.
