### ISSUE TITLE
Change the channel link in the contact section

### ISSUE THREAD

**Issue by saranshbarua** [osdc/osdc.github.io#46]
Since we are not using slack anymore, let's replace it with telegram.

**Comment by saranshbarua** [comment]
@Yugandhartripathi PTAL.

**Comment by saranshbarua** [comment]
Also, change the readme and update the maintainer.

**Comment by Yugandhartripathi** [comment]
#41 updated the link a while ago. It should be visible on netlify deployment.

**Comment by saranshbarua** [comment]
Yes, closing this now.
