### ISSUE TITLE
Change Club to Community

### ISSUE THREAD

**Issue by sidntrivedi** [osdc/osdc.github.io#50]
The website mentions OSDC as Open Source Developers Club. We need to change the Club to Community.

**Comment by ryzokuken** [comment]
@Yugandhartripathi @saranshbarua

**Comment by saranshbarua** [comment]
We'll have to make changes everywhere and also I'm not sure about changing the name. If everyone agrees then it's fine by me.

**Comment by ryzokuken** [comment]
Let me know by DM if you need me to change the org name on GitHub.

**Comment by sidntrivedi** [comment]
@saranshbarua Oh ! right. If we change the website name, we need to change it everywhere. Nvm, we can go on with this. Thanks. Closing it for now.
