### ISSUE TITLE
Add Twitter button to the website

### ISSUE THREAD

**Issue by sidntrivedi** [osdc/osdc.github.io#51]
Since, now we are active on twitter too we should add the link to twitter page of OSDC too.

OSDC Twitter - https://twitter.com/osdcjiit

Thanks 😃

**Comment by Yugandhartripathi** [comment]
![image](https://user-images.githubusercontent.com/32102845/64024349-c3423480-cb57-11e9-9947-940e91210c64.png)

Colour suggestions?

**Comment by sidntrivedi** [comment]
Ig, we can use #3b5998 for Facebook. A little darkish blue. What do you say?

**Comment by Yugandhartripathi** [comment]
![image](https://user-images.githubusercontent.com/32102845/64025138-aa3a8300-cb59-11e9-826f-60de9b1b38d9.png)
Nah, It's looking dull like the link is disabled

**Comment by saranshbarua** [comment]
Make sure this is responsive.

> ![image](https://user-images.githubusercontent.com/32102845/64024349-c3423480-cb57-11e9-9947-940e91210c64.png)
> 
> Colour suggestions?

**Comment by sidntrivedi012** [comment]
@Yugandhartripathi Umm..yes. Can we use any shade of azure or cyan?

**Comment by saranshbarua** [comment]
Let's not focus on colours too much as we'll be discussing the design again anytime soon. Plus this looks okayish too

**Comment by saranshbarua** [comment]
Also please post the screenshots for smaller devices if they're available.

**Comment by Yugandhartripathi** [comment]
On a 5.7" mobile device<br>
![osdc-jiitMobile](https://user-images.githubusercontent.com/32102845/64029253-da861f80-cb61-11e9-9411-b758bf5ad6ff.jpeg)
