### ISSUE TITLE
Update the deprecated blog link on website

### ISSUE THREAD

**Issue by feynon** [osdc/osdc.github.io#61]
# Changes to be made

Update the deprecated blog's link on the osdc official website to the current one addressed [here](https://osdcblog.netlify.app/).

------
 
*Hi, If it is the first time that you contribute to the repo, follow these steps:*

Write a comment in this issue thread to let other possible contributors know that you are working on this issue. For eg : `Hey all, I would like to work on this issue.`

**Comment by fizgenix** [comment]
I would like to work on this.

**Comment by daemon1024** [comment]
@fizgenix Thanks for showing interest 😁 Feel free to work on it and ask any queries regarding it in this thread ✌️☺️

**Comment by sidntrivedi** [comment]
Closed by #62
