### ISSUE TITLE
Adding a static site generator

### ISSUE THREAD

**Issue by 526avijitgupta** [osdc/osdc.github.io#8]
Dividing into multiple sub-tasks:

- [ ] Deciding on which static site generator to use:

* The most popular ones are Jekyll, Metalsmith, Hugo, Middleman etc. 
* We can also consider building our own static site generator from the ground up for finer control !

- [ ] Having the basic setup in place

**Comment by ryzokuken** [comment]
For now, we could just use Gulp.

**Comment by 526avijitgupta** [comment]
@ryzokuken 
* Better to use npm scripts instead of gulp/grunt - I mean, have a look at this: https://medium.freecodecamp.org/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8

* We'll have to write our custom css and styling ourselves then. I'm not sure if investing time into that is worth it

**Comment by priyansh1161** [comment]
@526avijitgupta 

- we should definitely opt for npm scripts for task automation.
- writing our own CSS means more contribution from newbies and a finer control over things, however, it's definitely time-consuming.

**Comment by octamois** [comment]
@priyansh1161 
Is time at which we are more concerned? , I mean that that investment of time can prove to be a boon.

**Comment by saranshbarua** [comment]
@526avijitgupta @ryzokuken @priyansh1161  do we still need this?

**Comment by ryzokuken** [comment]
@saranshbarua we don't we're using Gatsby. Closing this.
